One Hot Encoding using get dummies

In [25]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [65]:
data=pd.read_csv("index.csv")
data.head(5)

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [66]:
data.isnull().sum()

date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
dtype: int64

In [67]:
data["card"].fillna(data["card"].mode()[0] , inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_12828\393892547.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["card"].fillna(data["card"].mode()[0] , inplace=True)

In [68]:
data.isnull().sum()

date           0
datetime       0
cash_type      0
card           0
money          0
coffee_name    0
dtype: int64

In [69]:
en = data["cash_type"]
df=pd.get_dummies(en)
df

      card   cash
0     True  False
1     True  False
2     True  False
3     True  False
4     True  False
...    ...    ...
1128  True  False
1129  True  False
1130  True  False
1131  True  False
1132  True  False

[1133 rows x 2 columns]

In [70]:
df.head()

   card   cash
0  True  False
1  True  False
2  True  False
3  True  False
4  True  False

In [71]:
data =pd.concat([df , data] , axis = "columns")

In [72]:
data.head()

,card,cash,date,datetime,cash_type,card,money,coffee_name
0,True,False,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,True,False,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,True,False,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,True,False,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,True,False,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [73]:
data.drop("cash_type" , axis = "columns" , inplace = True)

In [74]:
data.head()

,card,cash,date,datetime,card,money,coffee_name
0,True,False,2024-03-01,2024-03-01 10:15:50.520,ANON-0000-0000-0001,38.7,Latte
1,True,False,2024-03-01,2024-03-01 12:19:22.539,ANON-0000-0000-0002,38.7,Hot Chocolate
2,True,False,2024-03-01,2024-03-01 12:20:18.089,ANON-0000-0000-0002,38.7,Hot Chocolate
3,True,False,2024-03-01,2024-03-01 13:46:33.006,ANON-0000-0000-0003,28.9,Americano
4,True,False,2024-03-01,2024-03-01 13:48:14.626,ANON-0000-0000-0004,38.7,Latte